// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/type.go
//
// Generated by this command:
//
//	mockgen -source=internal/application/type.go -aux_files registration-saga-service/internal/domain=internal/domain/session.go,registration-saga-service/internal/presentation/event_broker=internal/presentation/event_broker/type.go -destination=internal/fx/app_mock_test.go -package=appfx
//

// Package appfx is a generated GoMock package.
package appfx

import (
	context "context"
	reflect "reflect"
	service "registration-saga-service/internal/application"
	domain "registration-saga-service/internal/domain"

	gomock "go.uber.org/mock/gomock"
)

// MockRegistrationService is a mock of RegistrationService interface.
type MockRegistrationService struct {
	ctrl     *gomock.Controller
	recorder *MockRegistrationServiceMockRecorder
	isgomock struct{}
}

// MockRegistrationServiceMockRecorder is the mock recorder for MockRegistrationService.
type MockRegistrationServiceMockRecorder struct {
	mock *MockRegistrationService
}

// NewMockRegistrationService creates a new mock instance.
func NewMockRegistrationService(ctrl *gomock.Controller) *MockRegistrationService {
	mock := &MockRegistrationService{ctrl: ctrl}
	mock.recorder = &MockRegistrationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistrationService) EXPECT() *MockRegistrationServiceMockRecorder {
	return m.recorder
}

// GetRegistrationStatus mocks base method.
func (m *MockRegistrationService) GetRegistrationStatus(ctx context.Context, sessionID, clientID string) (*domain.RegistrationStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegistrationStatus", ctx, sessionID, clientID)
	ret0, _ := ret[0].(*domain.RegistrationStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegistrationStatus indicates an expected call of GetRegistrationStatus.
func (mr *MockRegistrationServiceMockRecorder) GetRegistrationStatus(ctx, sessionID, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegistrationStatus", reflect.TypeOf((*MockRegistrationService)(nil).GetRegistrationStatus), ctx, sessionID, clientID)
}

// HandleAuthCreatePendingResult mocks base method.
func (m *MockRegistrationService) HandleAuthCreatePendingResult(ctx context.Context, result service.AuthCreatePendingResult) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleAuthCreatePendingResult", ctx, result)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleAuthCreatePendingResult indicates an expected call of HandleAuthCreatePendingResult.
func (mr *MockRegistrationServiceMockRecorder) HandleAuthCreatePendingResult(ctx, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleAuthCreatePendingResult", reflect.TypeOf((*MockRegistrationService)(nil).HandleAuthCreatePendingResult), ctx, result)
}

// HandleMailSendResult mocks base method.
func (m *MockRegistrationService) HandleMailSendResult(ctx context.Context, result service.MailSendResult) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleMailSendResult", ctx, result)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleMailSendResult indicates an expected call of HandleMailSendResult.
func (mr *MockRegistrationServiceMockRecorder) HandleMailSendResult(ctx, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleMailSendResult", reflect.TypeOf((*MockRegistrationService)(nil).HandleMailSendResult), ctx, result)
}

// HandleUserCreateResult mocks base method.
func (m *MockRegistrationService) HandleUserCreateResult(ctx context.Context, result service.UserCreateResult) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleUserCreateResult", ctx, result)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleUserCreateResult indicates an expected call of HandleUserCreateResult.
func (mr *MockRegistrationServiceMockRecorder) HandleUserCreateResult(ctx, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleUserCreateResult", reflect.TypeOf((*MockRegistrationService)(nil).HandleUserCreateResult), ctx, result)
}

// Start mocks base method.
func (m *MockRegistrationService) Start(ctx context.Context, params domain.StartRegistrationParams) (*domain.StartRegistrationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, params)
	ret0, _ := ret[0].(*domain.StartRegistrationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Start indicates an expected call of Start.
func (mr *MockRegistrationServiceMockRecorder) Start(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockRegistrationService)(nil).Start), ctx, params)
}

// VerifyEmail mocks base method.
func (m *MockRegistrationService) VerifyEmail(ctx context.Context, params domain.VerifyEmailParams) (*domain.VerifyEmailResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyEmail", ctx, params)
	ret0, _ := ret[0].(*domain.VerifyEmailResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyEmail indicates an expected call of VerifyEmail.
func (mr *MockRegistrationServiceMockRecorder) VerifyEmail(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyEmail", reflect.TypeOf((*MockRegistrationService)(nil).VerifyEmail), ctx, params)
}

// MockEmailAvailabilityChecker is a mock of EmailAvailabilityChecker interface.
type MockEmailAvailabilityChecker struct {
	ctrl     *gomock.Controller
	recorder *MockEmailAvailabilityCheckerMockRecorder
	isgomock struct{}
}

// MockEmailAvailabilityCheckerMockRecorder is the mock recorder for MockEmailAvailabilityChecker.
type MockEmailAvailabilityCheckerMockRecorder struct {
	mock *MockEmailAvailabilityChecker
}

// NewMockEmailAvailabilityChecker creates a new mock instance.
func NewMockEmailAvailabilityChecker(ctrl *gomock.Controller) *MockEmailAvailabilityChecker {
	mock := &MockEmailAvailabilityChecker{ctrl: ctrl}
	mock.recorder = &MockEmailAvailabilityCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailAvailabilityChecker) EXPECT() *MockEmailAvailabilityCheckerMockRecorder {
	return m.recorder
}

// DeactivateRegistrationAuth mocks base method.
func (m *MockEmailAvailabilityChecker) DeactivateRegistrationAuth(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateRegistrationAuth", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateRegistrationAuth indicates an expected call of DeactivateRegistrationAuth.
func (mr *MockEmailAvailabilityCheckerMockRecorder) DeactivateRegistrationAuth(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateRegistrationAuth", reflect.TypeOf((*MockEmailAvailabilityChecker)(nil).DeactivateRegistrationAuth), ctx, userID)
}

// ExistsByEmail mocks base method.
func (m *MockEmailAvailabilityChecker) ExistsByEmail(ctx context.Context, email string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByEmail", ctx, email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByEmail indicates an expected call of ExistsByEmail.
func (mr *MockEmailAvailabilityCheckerMockRecorder) ExistsByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByEmail", reflect.TypeOf((*MockEmailAvailabilityChecker)(nil).ExistsByEmail), ctx, email)
}

// VerifyRegistrationEmail mocks base method.
func (m *MockEmailAvailabilityChecker) VerifyRegistrationEmail(ctx context.Context, userID, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyRegistrationEmail", ctx, userID, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyRegistrationEmail indicates an expected call of VerifyRegistrationEmail.
func (mr *MockEmailAvailabilityCheckerMockRecorder) VerifyRegistrationEmail(ctx, userID, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyRegistrationEmail", reflect.TypeOf((*MockEmailAvailabilityChecker)(nil).VerifyRegistrationEmail), ctx, userID, code)
}

// MockUsernameAvailabilityChecker is a mock of UsernameAvailabilityChecker interface.
type MockUsernameAvailabilityChecker struct {
	ctrl     *gomock.Controller
	recorder *MockUsernameAvailabilityCheckerMockRecorder
	isgomock struct{}
}

// MockUsernameAvailabilityCheckerMockRecorder is the mock recorder for MockUsernameAvailabilityChecker.
type MockUsernameAvailabilityCheckerMockRecorder struct {
	mock *MockUsernameAvailabilityChecker
}

// NewMockUsernameAvailabilityChecker creates a new mock instance.
func NewMockUsernameAvailabilityChecker(ctrl *gomock.Controller) *MockUsernameAvailabilityChecker {
	mock := &MockUsernameAvailabilityChecker{ctrl: ctrl}
	mock.recorder = &MockUsernameAvailabilityCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsernameAvailabilityChecker) EXPECT() *MockUsernameAvailabilityCheckerMockRecorder {
	return m.recorder
}

// ActivateUser mocks base method.
func (m *MockUsernameAvailabilityChecker) ActivateUser(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivateUser indicates an expected call of ActivateUser.
func (mr *MockUsernameAvailabilityCheckerMockRecorder) ActivateUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateUser", reflect.TypeOf((*MockUsernameAvailabilityChecker)(nil).ActivateUser), ctx, userID)
}

// DeactivateUser mocks base method.
func (m *MockUsernameAvailabilityChecker) DeactivateUser(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateUser indicates an expected call of DeactivateUser.
func (mr *MockUsernameAvailabilityCheckerMockRecorder) DeactivateUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateUser", reflect.TypeOf((*MockUsernameAvailabilityChecker)(nil).DeactivateUser), ctx, userID)
}

// ExistsByUsername mocks base method.
func (m *MockUsernameAvailabilityChecker) ExistsByUsername(ctx context.Context, username string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByUsername", ctx, username)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByUsername indicates an expected call of ExistsByUsername.
func (mr *MockUsernameAvailabilityCheckerMockRecorder) ExistsByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByUsername", reflect.TypeOf((*MockUsernameAvailabilityChecker)(nil).ExistsByUsername), ctx, username)
}

// MockRegistrationMessageMapper is a mock of RegistrationMessageMapper interface.
type MockRegistrationMessageMapper struct {
	ctrl     *gomock.Controller
	recorder *MockRegistrationMessageMapperMockRecorder
	isgomock struct{}
}

// MockRegistrationMessageMapperMockRecorder is the mock recorder for MockRegistrationMessageMapper.
type MockRegistrationMessageMapperMockRecorder struct {
	mock *MockRegistrationMessageMapper
}

// NewMockRegistrationMessageMapper creates a new mock instance.
func NewMockRegistrationMessageMapper(ctrl *gomock.Controller) *MockRegistrationMessageMapper {
	mock := &MockRegistrationMessageMapper{ctrl: ctrl}
	mock.recorder = &MockRegistrationMessageMapperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistrationMessageMapper) EXPECT() *MockRegistrationMessageMapperMockRecorder {
	return m.recorder
}

// ToAuthCreatePendingCommandPayload mocks base method.
func (m *MockRegistrationMessageMapper) ToAuthCreatePendingCommandPayload(session domain.Session, email, passwordHash string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToAuthCreatePendingCommandPayload", session, email, passwordHash)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToAuthCreatePendingCommandPayload indicates an expected call of ToAuthCreatePendingCommandPayload.
func (mr *MockRegistrationMessageMapperMockRecorder) ToAuthCreatePendingCommandPayload(session, email, passwordHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToAuthCreatePendingCommandPayload", reflect.TypeOf((*MockRegistrationMessageMapper)(nil).ToAuthCreatePendingCommandPayload), session, email, passwordHash)
}

// ToCodeSentEventPayload mocks base method.
func (m *MockRegistrationMessageMapper) ToCodeSentEventPayload(result service.MailSendResult) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToCodeSentEventPayload", result)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToCodeSentEventPayload indicates an expected call of ToCodeSentEventPayload.
func (mr *MockRegistrationMessageMapperMockRecorder) ToCodeSentEventPayload(result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToCodeSentEventPayload", reflect.TypeOf((*MockRegistrationMessageMapper)(nil).ToCodeSentEventPayload), result)
}

// ToCompletedConflictResult mocks base method.
func (m *MockRegistrationMessageMapper) ToCompletedConflictResult(emailTaken, usernameTaken bool) *domain.StartRegistrationResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToCompletedConflictResult", emailTaken, usernameTaken)
	ret0, _ := ret[0].(*domain.StartRegistrationResult)
	return ret0
}

// ToCompletedConflictResult indicates an expected call of ToCompletedConflictResult.
func (mr *MockRegistrationMessageMapperMockRecorder) ToCompletedConflictResult(emailTaken, usernameTaken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToCompletedConflictResult", reflect.TypeOf((*MockRegistrationMessageMapper)(nil).ToCompletedConflictResult), emailTaken, usernameTaken)
}

// ToIncompleteConflictResult mocks base method.
func (m *MockRegistrationMessageMapper) ToIncompleteConflictResult(emailSession, usernameSession *domain.Session) *domain.StartRegistrationResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToIncompleteConflictResult", emailSession, usernameSession)
	ret0, _ := ret[0].(*domain.StartRegistrationResult)
	return ret0
}

// ToIncompleteConflictResult indicates an expected call of ToIncompleteConflictResult.
func (mr *MockRegistrationMessageMapperMockRecorder) ToIncompleteConflictResult(emailSession, usernameSession any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToIncompleteConflictResult", reflect.TypeOf((*MockRegistrationMessageMapper)(nil).ToIncompleteConflictResult), emailSession, usernameSession)
}

// ToRegistrationCompletedEventPayload mocks base method.
func (m *MockRegistrationMessageMapper) ToRegistrationCompletedEventPayload(session domain.Session) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToRegistrationCompletedEventPayload", session)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToRegistrationCompletedEventPayload indicates an expected call of ToRegistrationCompletedEventPayload.
func (mr *MockRegistrationMessageMapperMockRecorder) ToRegistrationCompletedEventPayload(session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToRegistrationCompletedEventPayload", reflect.TypeOf((*MockRegistrationMessageMapper)(nil).ToRegistrationCompletedEventPayload), session)
}

// ToRegistrationFailedEventPayload mocks base method.
func (m *MockRegistrationMessageMapper) ToRegistrationFailedEventPayload(session domain.Session, reason string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToRegistrationFailedEventPayload", session, reason)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToRegistrationFailedEventPayload indicates an expected call of ToRegistrationFailedEventPayload.
func (mr *MockRegistrationMessageMapperMockRecorder) ToRegistrationFailedEventPayload(session, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToRegistrationFailedEventPayload", reflect.TypeOf((*MockRegistrationMessageMapper)(nil).ToRegistrationFailedEventPayload), session, reason)
}

// ToUserCreateCommandPayload mocks base method.
func (m *MockRegistrationMessageMapper) ToUserCreateCommandPayload(session domain.Session, firstName, surname string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToUserCreateCommandPayload", session, firstName, surname)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToUserCreateCommandPayload indicates an expected call of ToUserCreateCommandPayload.
func (mr *MockRegistrationMessageMapperMockRecorder) ToUserCreateCommandPayload(session, firstName, surname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToUserCreateCommandPayload", reflect.TypeOf((*MockRegistrationMessageMapper)(nil).ToUserCreateCommandPayload), session, firstName, surname)
}
