// Code generated by MockGen. DO NOT EDIT.
// Source: /home/alex/projects/ofm-microservices/ofm-registration-saga-service/internal/domain/session.go
//
// Generated by this command:
//
//	mockgen -source=/home/alex/projects/ofm-microservices/ofm-registration-saga-service/internal/domain/session.go -destination=/home/alex/projects/ofm-microservices/ofm-registration-saga-service/internal/application/deps_mock_test.go -package=service
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"
	domain "registration-saga-service/internal/domain"

	gomock "go.uber.org/mock/gomock"
)

// MockSessionRepository is a mock of SessionRepository interface.
type MockSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepositoryMockRecorder
	isgomock struct{}
}

// MockSessionRepositoryMockRecorder is the mock recorder for MockSessionRepository.
type MockSessionRepositoryMockRecorder struct {
	mock *MockSessionRepository
}

// NewMockSessionRepository creates a new mock instance.
func NewMockSessionRepository(ctrl *gomock.Controller) *MockSessionRepository {
	mock := &MockSessionRepository{ctrl: ctrl}
	mock.recorder = &MockSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepository) EXPECT() *MockSessionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSessionRepository) Create(ctx context.Context, session domain.Session) (*domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, session)
	ret0, _ := ret[0].(*domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSessionRepositoryMockRecorder) Create(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSessionRepository)(nil).Create), ctx, session)
}

// GetByEmail mocks base method.
func (m *MockSessionRepository) GetByEmail(ctx context.Context, email string) (*domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(*domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockSessionRepositoryMockRecorder) GetByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockSessionRepository)(nil).GetByEmail), ctx, email)
}

// GetByID mocks base method.
func (m *MockSessionRepository) GetByID(ctx context.Context, sessionID string) (*domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, sessionID)
	ret0, _ := ret[0].(*domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockSessionRepositoryMockRecorder) GetByID(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockSessionRepository)(nil).GetByID), ctx, sessionID)
}

// GetByUsername mocks base method.
func (m *MockSessionRepository) GetByUsername(ctx context.Context, username string) (*domain.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUsername", ctx, username)
	ret0, _ := ret[0].(*domain.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUsername indicates an expected call of GetByUsername.
func (mr *MockSessionRepositoryMockRecorder) GetByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUsername", reflect.TypeOf((*MockSessionRepository)(nil).GetByUsername), ctx, username)
}

// UpdateStatus mocks base method.
func (m *MockSessionRepository) UpdateStatus(ctx context.Context, sessionID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, sessionID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockSessionRepositoryMockRecorder) UpdateStatus(ctx, sessionID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockSessionRepository)(nil).UpdateStatus), ctx, sessionID, status)
}

// MockStepRepository is a mock of StepRepository interface.
type MockStepRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStepRepositoryMockRecorder
	isgomock struct{}
}

// MockStepRepositoryMockRecorder is the mock recorder for MockStepRepository.
type MockStepRepositoryMockRecorder struct {
	mock *MockStepRepository
}

// NewMockStepRepository creates a new mock instance.
func NewMockStepRepository(ctrl *gomock.Controller) *MockStepRepository {
	mock := &MockStepRepository{ctrl: ctrl}
	mock.recorder = &MockStepRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStepRepository) EXPECT() *MockStepRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockStepRepository) Create(ctx context.Context, step domain.Step) (*domain.Step, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, step)
	ret0, _ := ret[0].(*domain.Step)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockStepRepositoryMockRecorder) Create(ctx, step any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStepRepository)(nil).Create), ctx, step)
}

// GetByKey mocks base method.
func (m *MockStepRepository) GetByKey(ctx context.Context, sessionID, stepKey string) (*domain.Step, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByKey", ctx, sessionID, stepKey)
	ret0, _ := ret[0].(*domain.Step)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByKey indicates an expected call of GetByKey.
func (mr *MockStepRepositoryMockRecorder) GetByKey(ctx, sessionID, stepKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByKey", reflect.TypeOf((*MockStepRepository)(nil).GetByKey), ctx, sessionID, stepKey)
}

// ListBySessionID mocks base method.
func (m *MockStepRepository) ListBySessionID(ctx context.Context, sessionID string) ([]domain.Step, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBySessionID", ctx, sessionID)
	ret0, _ := ret[0].([]domain.Step)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBySessionID indicates an expected call of ListBySessionID.
func (mr *MockStepRepositoryMockRecorder) ListBySessionID(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBySessionID", reflect.TypeOf((*MockStepRepository)(nil).ListBySessionID), ctx, sessionID)
}

// UpdateStatus mocks base method.
func (m *MockStepRepository) UpdateStatus(ctx context.Context, sessionID, stepKey, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, sessionID, stepKey, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockStepRepositoryMockRecorder) UpdateStatus(ctx, sessionID, stepKey, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockStepRepository)(nil).UpdateStatus), ctx, sessionID, stepKey, status)
}
