// Code generated by MockGen. DO NOT EDIT.
// Source: internal/presentation/grpc/type.go
//
// Generated by this command:
//
//	mockgen -source=internal/presentation/grpc/type.go -destination=internal/presentation/grpc/mock_test.go -package=grpc -aux_files registration-saga-service/internal/domain=internal/domain/session.go,registration-saga-service/internal/application=internal/application/type.go
//

// Package grpc is a generated GoMock package.
package grpc

import (
	context "context"
	reflect "reflect"
	domain "registration-saga-service/internal/domain"

	v1 "github.com/ofm-microseervices/ofm-common/proto/registration/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockServer is a mock of Server interface.
type MockServer struct {
	ctrl     *gomock.Controller
	recorder *MockServerMockRecorder
	isgomock struct{}
}

// MockServerMockRecorder is the mock recorder for MockServer.
type MockServerMockRecorder struct {
	mock *MockServer
}

// NewMockServer creates a new mock instance.
func NewMockServer(ctrl *gomock.Controller) *MockServer {
	mock := &MockServer{ctrl: ctrl}
	mock.recorder = &MockServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServer) EXPECT() *MockServerMockRecorder {
	return m.recorder
}

// Shutdown mocks base method.
func (m *MockServer) Shutdown(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockServerMockRecorder) Shutdown(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockServer)(nil).Shutdown), ctx)
}

// Start mocks base method.
func (m *MockServer) Start() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start")
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockServerMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockServer)(nil).Start))
}

// MockRegistrationMapper is a mock of RegistrationMapper interface.
type MockRegistrationMapper struct {
	ctrl     *gomock.Controller
	recorder *MockRegistrationMapperMockRecorder
	isgomock struct{}
}

// MockRegistrationMapperMockRecorder is the mock recorder for MockRegistrationMapper.
type MockRegistrationMapperMockRecorder struct {
	mock *MockRegistrationMapper
}

// NewMockRegistrationMapper creates a new mock instance.
func NewMockRegistrationMapper(ctrl *gomock.Controller) *MockRegistrationMapper {
	mock := &MockRegistrationMapper{ctrl: ctrl}
	mock.recorder = &MockRegistrationMapperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistrationMapper) EXPECT() *MockRegistrationMapperMockRecorder {
	return m.recorder
}

// ToStartError mocks base method.
func (m *MockRegistrationMapper) ToStartError(err error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToStartError", err)
	ret0, _ := ret[0].(error)
	return ret0
}

// ToStartError indicates an expected call of ToStartError.
func (mr *MockRegistrationMapperMockRecorder) ToStartError(err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToStartError", reflect.TypeOf((*MockRegistrationMapper)(nil).ToStartError), err)
}

// ToStartParams mocks base method.
func (m *MockRegistrationMapper) ToStartParams(req *v1.StartRegistrationRequest) domain.StartRegistrationParams {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToStartParams", req)
	ret0, _ := ret[0].(domain.StartRegistrationParams)
	return ret0
}

// ToStartParams indicates an expected call of ToStartParams.
func (mr *MockRegistrationMapperMockRecorder) ToStartParams(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToStartParams", reflect.TypeOf((*MockRegistrationMapper)(nil).ToStartParams), req)
}

// ToStartResponse mocks base method.
func (m *MockRegistrationMapper) ToStartResponse(result *domain.StartRegistrationResult) *v1.StartRegistrationResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToStartResponse", result)
	ret0, _ := ret[0].(*v1.StartRegistrationResponse)
	return ret0
}

// ToStartResponse indicates an expected call of ToStartResponse.
func (mr *MockRegistrationMapperMockRecorder) ToStartResponse(result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToStartResponse", reflect.TypeOf((*MockRegistrationMapper)(nil).ToStartResponse), result)
}
