// Code generated by MockGen. DO NOT EDIT.
// Source: /home/alex/projects/ofm-microservices/ofm-registration-saga-service/internal/application/type.go
//
// Generated by this command:
//
//	mockgen -source=/home/alex/projects/ofm-microservices/ofm-registration-saga-service/internal/application/type.go -destination=/home/alex/projects/ofm-microservices/ofm-registration-saga-service/internal/presentation/event_broker/nats/app_mock_test.go -package=nats -aux_files registration-saga-service/internal/domain=/home/alex/projects/ofm-microservices/ofm-registration-saga-service/internal/domain/session.go,registration-saga-service/internal/presentation/event_broker=/home/alex/projects/ofm-microservices/ofm-registration-saga-service/internal/presentation/event_broker/type.go
//

// Package nats is a generated GoMock package.
package nats

import (
	context "context"
	reflect "reflect"
	application "registration-saga-service/internal/application"
	domain "registration-saga-service/internal/domain"

	gomock "go.uber.org/mock/gomock"
)

// MockRegistrationService is a mock of RegistrationService interface.
type MockRegistrationService struct {
	ctrl     *gomock.Controller
	recorder *MockRegistrationServiceMockRecorder
	isgomock struct{}
}

// MockRegistrationServiceMockRecorder is the mock recorder for MockRegistrationService.
type MockRegistrationServiceMockRecorder struct {
	mock *MockRegistrationService
}

// NewMockRegistrationService creates a new mock instance.
func NewMockRegistrationService(ctrl *gomock.Controller) *MockRegistrationService {
	mock := &MockRegistrationService{ctrl: ctrl}
	mock.recorder = &MockRegistrationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistrationService) EXPECT() *MockRegistrationServiceMockRecorder {
	return m.recorder
}

// HandleAuthCreatePendingResult mocks base method.
func (m *MockRegistrationService) HandleAuthCreatePendingResult(ctx context.Context, result application.AuthCreatePendingResult) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleAuthCreatePendingResult", ctx, result)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleAuthCreatePendingResult indicates an expected call of HandleAuthCreatePendingResult.
func (mr *MockRegistrationServiceMockRecorder) HandleAuthCreatePendingResult(ctx, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleAuthCreatePendingResult", reflect.TypeOf((*MockRegistrationService)(nil).HandleAuthCreatePendingResult), ctx, result)
}

// HandleMailSendResult mocks base method.
func (m *MockRegistrationService) HandleMailSendResult(ctx context.Context, result application.MailSendResult) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleMailSendResult", ctx, result)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleMailSendResult indicates an expected call of HandleMailSendResult.
func (mr *MockRegistrationServiceMockRecorder) HandleMailSendResult(ctx, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleMailSendResult", reflect.TypeOf((*MockRegistrationService)(nil).HandleMailSendResult), ctx, result)
}

// HandleUserCreateResult mocks base method.
func (m *MockRegistrationService) HandleUserCreateResult(ctx context.Context, result application.UserCreateResult) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleUserCreateResult", ctx, result)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleUserCreateResult indicates an expected call of HandleUserCreateResult.
func (mr *MockRegistrationServiceMockRecorder) HandleUserCreateResult(ctx, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleUserCreateResult", reflect.TypeOf((*MockRegistrationService)(nil).HandleUserCreateResult), ctx, result)
}

// Start mocks base method.
func (m *MockRegistrationService) Start(ctx context.Context, params domain.StartRegistrationParams) (*domain.StartRegistrationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, params)
	ret0, _ := ret[0].(*domain.StartRegistrationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Start indicates an expected call of Start.
func (mr *MockRegistrationServiceMockRecorder) Start(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockRegistrationService)(nil).Start), ctx, params)
}

// MockEmailAvailabilityChecker is a mock of EmailAvailabilityChecker interface.
type MockEmailAvailabilityChecker struct {
	ctrl     *gomock.Controller
	recorder *MockEmailAvailabilityCheckerMockRecorder
	isgomock struct{}
}

// MockEmailAvailabilityCheckerMockRecorder is the mock recorder for MockEmailAvailabilityChecker.
type MockEmailAvailabilityCheckerMockRecorder struct {
	mock *MockEmailAvailabilityChecker
}

// NewMockEmailAvailabilityChecker creates a new mock instance.
func NewMockEmailAvailabilityChecker(ctrl *gomock.Controller) *MockEmailAvailabilityChecker {
	mock := &MockEmailAvailabilityChecker{ctrl: ctrl}
	mock.recorder = &MockEmailAvailabilityCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailAvailabilityChecker) EXPECT() *MockEmailAvailabilityCheckerMockRecorder {
	return m.recorder
}

// ExistsByEmail mocks base method.
func (m *MockEmailAvailabilityChecker) ExistsByEmail(ctx context.Context, email string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByEmail", ctx, email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByEmail indicates an expected call of ExistsByEmail.
func (mr *MockEmailAvailabilityCheckerMockRecorder) ExistsByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByEmail", reflect.TypeOf((*MockEmailAvailabilityChecker)(nil).ExistsByEmail), ctx, email)
}

// MockUsernameAvailabilityChecker is a mock of UsernameAvailabilityChecker interface.
type MockUsernameAvailabilityChecker struct {
	ctrl     *gomock.Controller
	recorder *MockUsernameAvailabilityCheckerMockRecorder
	isgomock struct{}
}

// MockUsernameAvailabilityCheckerMockRecorder is the mock recorder for MockUsernameAvailabilityChecker.
type MockUsernameAvailabilityCheckerMockRecorder struct {
	mock *MockUsernameAvailabilityChecker
}

// NewMockUsernameAvailabilityChecker creates a new mock instance.
func NewMockUsernameAvailabilityChecker(ctrl *gomock.Controller) *MockUsernameAvailabilityChecker {
	mock := &MockUsernameAvailabilityChecker{ctrl: ctrl}
	mock.recorder = &MockUsernameAvailabilityCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsernameAvailabilityChecker) EXPECT() *MockUsernameAvailabilityCheckerMockRecorder {
	return m.recorder
}

// ExistsByUsername mocks base method.
func (m *MockUsernameAvailabilityChecker) ExistsByUsername(ctx context.Context, username string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByUsername", ctx, username)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByUsername indicates an expected call of ExistsByUsername.
func (mr *MockUsernameAvailabilityCheckerMockRecorder) ExistsByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByUsername", reflect.TypeOf((*MockUsernameAvailabilityChecker)(nil).ExistsByUsername), ctx, username)
}

// MockRegistrationMessageMapper is a mock of RegistrationMessageMapper interface.
type MockRegistrationMessageMapper struct {
	ctrl     *gomock.Controller
	recorder *MockRegistrationMessageMapperMockRecorder
	isgomock struct{}
}

// MockRegistrationMessageMapperMockRecorder is the mock recorder for MockRegistrationMessageMapper.
type MockRegistrationMessageMapperMockRecorder struct {
	mock *MockRegistrationMessageMapper
}

// NewMockRegistrationMessageMapper creates a new mock instance.
func NewMockRegistrationMessageMapper(ctrl *gomock.Controller) *MockRegistrationMessageMapper {
	mock := &MockRegistrationMessageMapper{ctrl: ctrl}
	mock.recorder = &MockRegistrationMessageMapperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistrationMessageMapper) EXPECT() *MockRegistrationMessageMapperMockRecorder {
	return m.recorder
}

// ToAuthCreatePendingCommandPayload mocks base method.
func (m *MockRegistrationMessageMapper) ToAuthCreatePendingCommandPayload(session domain.Session, email, passwordHash string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToAuthCreatePendingCommandPayload", session, email, passwordHash)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToAuthCreatePendingCommandPayload indicates an expected call of ToAuthCreatePendingCommandPayload.
func (mr *MockRegistrationMessageMapperMockRecorder) ToAuthCreatePendingCommandPayload(session, email, passwordHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToAuthCreatePendingCommandPayload", reflect.TypeOf((*MockRegistrationMessageMapper)(nil).ToAuthCreatePendingCommandPayload), session, email, passwordHash)
}

// ToCodeSentEventPayload mocks base method.
func (m *MockRegistrationMessageMapper) ToCodeSentEventPayload(result application.MailSendResult) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToCodeSentEventPayload", result)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToCodeSentEventPayload indicates an expected call of ToCodeSentEventPayload.
func (mr *MockRegistrationMessageMapperMockRecorder) ToCodeSentEventPayload(result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToCodeSentEventPayload", reflect.TypeOf((*MockRegistrationMessageMapper)(nil).ToCodeSentEventPayload), result)
}

// ToCompletedConflictResult mocks base method.
func (m *MockRegistrationMessageMapper) ToCompletedConflictResult(emailTaken, usernameTaken bool) *domain.StartRegistrationResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToCompletedConflictResult", emailTaken, usernameTaken)
	ret0, _ := ret[0].(*domain.StartRegistrationResult)
	return ret0
}

// ToCompletedConflictResult indicates an expected call of ToCompletedConflictResult.
func (mr *MockRegistrationMessageMapperMockRecorder) ToCompletedConflictResult(emailTaken, usernameTaken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToCompletedConflictResult", reflect.TypeOf((*MockRegistrationMessageMapper)(nil).ToCompletedConflictResult), emailTaken, usernameTaken)
}

// ToIncompleteConflictResult mocks base method.
func (m *MockRegistrationMessageMapper) ToIncompleteConflictResult(emailSession, usernameSession *domain.Session) *domain.StartRegistrationResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToIncompleteConflictResult", emailSession, usernameSession)
	ret0, _ := ret[0].(*domain.StartRegistrationResult)
	return ret0
}

// ToIncompleteConflictResult indicates an expected call of ToIncompleteConflictResult.
func (mr *MockRegistrationMessageMapperMockRecorder) ToIncompleteConflictResult(emailSession, usernameSession any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToIncompleteConflictResult", reflect.TypeOf((*MockRegistrationMessageMapper)(nil).ToIncompleteConflictResult), emailSession, usernameSession)
}

// ToUserCreateCommandPayload mocks base method.
func (m *MockRegistrationMessageMapper) ToUserCreateCommandPayload(session domain.Session, firstName, surname string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToUserCreateCommandPayload", session, firstName, surname)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToUserCreateCommandPayload indicates an expected call of ToUserCreateCommandPayload.
func (mr *MockRegistrationMessageMapperMockRecorder) ToUserCreateCommandPayload(session, firstName, surname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToUserCreateCommandPayload", reflect.TypeOf((*MockRegistrationMessageMapper)(nil).ToUserCreateCommandPayload), session, firstName, surname)
}
